name: MDeath
main: ca.q0r.mdeath.MDeath
version: ${version}-${build.number}
author: ryan_the_leach
authors: [ryan_the_leach]
website: http://mdev.in/
softdepend: [mChatSuite, MChat, Spout, SpoutPlugin]
description: Death message formatting for MChat
commands:
    mdeath:
        aliases: [mdth, md]
        ~permissions: mdeath.reload
permissions:
    mdeath.*:
        default: op
        description: Allows full use of MDeath.
        children:
            mdeath.reload: true
    mdeath.reload:
        default: false
        description: Allow usage of /mdeath reload command.